### ISSUE TITLE
"Turn off" bug

### ISSUE THREAD

**Issue by Ittiz** [MycroftAI/skill-stop#29]
You must have recently updated this to be more flexible with the use of the phrase "turn off" because this skill now conflicts with my Domoticz Skill. Now when I say something like "turn off the lights" and instead of turning off the lights it asks "confirming, you want me to turn myself off?"  It's annoying.  The skill should require something like "yourself"

**Comment by forslund** [comment]
I believe this has been resolved by PR #30. I'm closing this one, if you have further issues feel free to reopen this Issue.
